<?php
define('TABLE_USERS','user_profile');
define('TABLE_GOLF_USERS','golf_users');
define('_GOLF_COURSE_TBL_','golf_course');
define('_CITY_TBL_','city');
define('_COUNTRY_TBL_','country');
define('_STATE_TBL_','state');
define('_EVENT_TBL_','event_table');
define('_EVENT_LIST_VIEW_','event_list_view');
define('_GOLF_COURSE_TEE_TBL_','golf_course_tee');
define('_GAME_FORMAT_TBL_','game_format');
define('_TEE_TBL_','tee');
define('_EVENT_FORMAT_TBL_','event_format');
define('_EVENT_TYPE_TBL_','event_type');
define('_EVENT_PLAYER_LIST_TBL_','event_player_list');
define('_GROUP_MEMBER_LIST_','golf_group_members');
define('_GROUP_LIST_','golf_group');
define('_EVENT_BANNER_','golf_banners');
?>
